### ISSUE TITLE
Is 1.20.1 Purpur/Paper Supported?

### ISSUE THREAD

**Issue by JACKKY04** [paul-eff/MinecraftOfflineOnlineConverter#1]
Need to Migrate my server from offline mode to online mode whilst keeping all player data and their inventories. Is this possible with this tool?

**Comment by paul-eff** [comment]
Based on what I can see, there haven't been any significant changes in the structure of how Paper saves its player data. Therefore, Paper should still be fully supported. Purpur appears to be a fork of Paper, so it's reasonable to assume that it will also be supported.

However, as a precaution, please make a backup before proceeding. My best guess is that it will work without any issues.

**Comment by paul-eff** [comment]
@JACKKY04 Paper and Purpur (v1.20.1) were and still are fully supported.
It's tested and accompanied by a [new release](https://github.com/paul-eff/MinecraftOfflineOnlineConverter/releases/tag/2.3.3).

**Comment by Catzzye** [comment]
@paul-eff Sorry to necro an old issue, but do you have any idea if this tool works with 1.21.? I just manually did this with my server, but I found that everything but the inventory still got reset so I want to try this tool. It's cool if it's not, just wanna know before trying to running it on my server, thank you xx :)

**Comment by paul-eff** [comment]
Hi @Catzzye, no problem. I just did a quick test and the current v2.3.4 can handle Paper 1.21 (Build 119) just fine.
My local server retained inventory, position, advancements and statistics.

As stated above, Purpur is a Paper fork, I am fairly confident this will also apply to it.

**Comment by Catzzye** [comment]
Hii @paul-eff. Thank you for the very fast reply. 
That's great to hear, I've got that done and dusted! One of my players asked a very specific question (it's a bit off topic). He worked hard to earn 'villager discounts' on trades, do you have any clue whatsoever where that might be stored? I can see that inventory, advancements and statistics carried over, with position being reset because of the register/login plugin I use, but I cannot find anything online about those villager trade parameters. If you have no idea that's cool no worries, I found no info about it online, and quick scour through the .dat I didn't really find anything of the sorts. 

Cheers (:

**Comment by paul-eff** [comment]
No problem @Catzzye :) I had another minute and was able to confirm that Purpur, as I suspected, is working fine.
Good to hear that it also worked for you!

Regarding the villagers, I sadly don't know.
My best guess, as Minecraft saves other entity/block parameters the same is, that it is stored "in" the villager.
In the world folder you can find an entities directory, that's probably where you have to start looking. But you'd probably have to go down a deep rabbit hole to find exactly that villager and modify his trades to your liking.
It's probably best to get a plugin that can modify entity metadata in game :(.

Cheers mate!

**Comment by Catzzye** [comment]
That would make a lot of sense actually, thank you so much for the very prompt info and your time!!
