### ISSUE TITLE
FTB support

### ISSUE THREAD

**Issue by Furbysz** [paul-eff/MinecraftOfflineOnlineConverter#2]
Is there a way to target additional directories/files/binaries?
I tried using your tool to convert singleplayer LAN world into Offline server, but it seems that it totally ommited the FTBchunks, FTBquests, FTBteams, etc..

We were playing on Create: Arcane engineering 1.7

**Comment by paul-eff** [comment]
I can investigate this. It will take some time because I didn't initially consider modded servers. However, I don't currently see any reason why it shouldn't be possible.

My script essentially examines the standard Minecraft server files (both default and the world directory) and converts the discovered UUIDs from online to offline, or vice versa. If targeting additional directories is the solution, this should be a relatively quick fix.

Could you please provide me with information on what you've tried and what happened in the game as a result? For example, did some or all players not have their respective inventories?

**Comment by Furbysz** [comment]
Sorry for late reply. So basically, I'm a premium user, with frends who have premium and non-premium copies. 
We started playing on my LAN open world, but soon enought decided to migrate to server, becouse I couldn't have modded minecraft 24/7 in background.

I expected it to not go too smooth due to Premium-Lan to NonPremium-server jumping. 
I tried manually fix files, by manually replacing every [premum-player-uuid] with [nonpremium-player-uuid], with i aquired by geting onto both LAN and Server and typing `/list uuids`, Tried doing this proces after using your tool also, with to its credit helped a lot, but it seems like the UUIDS can hide EVERYWHERE within savegame folder due to mods using them universally.

I can l8er upload savegamefolder somewhere for you to look trought, but tbh rn my bros came back to school anyways. I'm just aiming to finish what i iniciated and mebe help someone in the future :)

**Comment by paul-eff** [comment]
Yeah I understand your problem just to good.
I'll try to think something up for modded servers and investigate myself if mods etc. really use UUIDs in every corner of the server's directory.
I'll keep you posted if I have a breakthrough.
Feel free to add information to this issue if you find anything new.

**Comment by paul-eff** [comment]
Hi @Furbysz ,

sorry it took so long! At the time I was wrapped up in uni and life. Then I just forgot.
[Here is a pre-release](https://github.com/paul-eff/MinecraftOfflineOnlineConverter/releases/tag/v3-beta.1) that works fine, but needs some polishing.

For now you will have to target the mods folder etc. yourself by adding them to the custom_paths.yml file. I will try to come up with something myself. If you have any findings, feel free to share with me.

Have a good one. Don't forget to backup before using!
Please open a new ticket if something is not working.
